name: firebase_picture_uploader
description: Picture upload widget which helps selecting and uploading one or multiple images to firebase storage.
version: 1.2.1
homepage: https://github.com/Rodiii/flutter_firebase_picture_uploader
maintainer: Christoph Rothermel (@rothech)

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cached_network_image: ^2.5.0
  firebase_storage: ^7.0.0
  firebase_core: ^0.7.0 
  image: ^2.1.19
  image_picker: ^0.6.7+22
  image_cropper: ^1.3.1
  shared_preferences: ^0.5.12+4
  path_provider: ^1.6.27
  cupertino_icons: ^1.0.0 


dev_dependencies:
  flutter_test:
    sdk: flutter
 